CREATE TABLE `board` (
     `id` BIGINT(19) NOT NULL AUTO_INCREMENT,
     `reg_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 날짜',
     `title` VARCHAR(255) NULL DEFAULT NULL COMMENT '제목',
     `content` VARCHAR(255) NULL DEFAULT NULL COMMENT '내용',
     PRIMARY KEY (`id`) USING BTREE
)
;
